### ISSUE TITLE
Add additional communication mode mechanism via Nearby Messages

### ISSUE THREAD

**Issue by typelogic** [idpass/smartshare-react-native#7]
**Is your feature request related to a problem? Please describe.**
This is a react-native changes needed to accommodate https://github.com/idpass/idpass-smartshare/issues/4 

**Describe the solution you'd like**
This is a smartshare-react-native changes needed to accommodate the changes in `smartshare.aar` library  

**Additional context**
The React Native wrapper of `smartshare.aar` to have an option to use `Nearby Message` communication mode for: 

- Android <-> IOS communication.
- Android <-> Android communication
- IOS <-> IOS communication

**Comment by pmigueld** [comment]
Google Nearby Messages added to Smartshare library:
https://github.com/idpass/smartshare-react-native/tree/feature/nearby-messages

It is now possible to communicate between iOS and Android.
